theme: jekyll-theme-hacker
title: Pride and Roses
description: This is DragonKnightRose's submission for the Summer 2019 edition of "My First Game Jam". (https://github.com/DragonKnightRose/MyFirstGameJamSumer2019.git)
